tasks:
  - init: >
      sudo apt update && sudo apt upgrade -y && virtualenv venv && source venv/bin/activate && python -m pip install --upgrade pip && pip install -r requirements.txt
      python __init__.py