name: update docset

# Controls when the workflow will run
on:
  # Triggers the workflow on push events and only for the main branch
  push:
    branches: [main]
  pull_request:
    branches-ignore: [main]
  schedule:
    - cron: "35 5 * * 1" # every Monday at 5:35AM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  repository_dispatch: # run workflow on api request

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: clone this repo
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY requests_docset_gh

      - name: update packages
        run: timeout 100s sudo apt update || true

      - name: upgrade packages
        run: timeout 180s sudo apt upgrade -y || true

      - name: Setup Python 3.x
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.11.0
          cache: "pip"

      - name: upgrade pip
        run: python -m pip install --upgrade pip

      - name: install virtualenv
        run: pip install virtualenv

      - name: list directory contents
        run: ls -lisha

      - name: init virtualenv
        run: virtualenv venv

      - name: activate virtualenv
        run: source venv/bin/activate

      - name: list directory contents
        run: ls -lisha

      - name: install python requirements
        run: pip install -r requests_docset_gh/requirements.txt

      - name: run python script
        run: cd requests_docset_gh && timeout 180s python __init__.py

      - name: list directory contents of requests_docset_gh
        run: ls -lisha requests_docset_gh/

      - name: list directory contents of working dir
        run: ls -lisha

      - name: return directory size of working dir
        run: timeout 60s du -sh

      - uses: actions/upload-artifact@v3
        with:
          path: "requests_docset_gh/Requests.docset/"
          name: "Requests.docset"
          retention-days: 5

      # - name: git push to github
      #   run: |
      #     cd requests_docset_gh
      #     git config --global user.name ''
      #     git config --global user.email ''
      #     git remote add github-origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      #     git fetch --all
      #     git checkout 'main'
      #     git reset
      #     git add Requests.docset/ || true
      #     git status
      #     git commit -m "update docset" || true
      #     git push github-origin main || true
